# -*- coding: utf-8 -*-
"""Datetime.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XgR-H_RtdpM0naP_3KASOpAapNTtfEPV
"""

import datetime
today = datetime.date.today()
print(today)
today = str(today)
year = int(today[0:4])
month = int(today[5:7])
day = int(today[8:])

days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)
    leapyear_days = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)# if a year is divisible by 4 it is a leap year unless it is divisible by 100 and not by 400
number_of_days = 0
for years in range (0, year):
    if years %4 == 0 and years %100 != 0:
        number_of_days += 366
    elif years %400 == 0:
        number_of_days += 366
    else:
        number_of_days += 365

if year %
for months in range(0, month):


print(number_of_days)