# -*- coding: utf-8 -*-
"""Datetime.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XgR-H_RtdpM0naP_3KASOpAapNTtfEPV
"""

import datetime
today = datetime.date.today()
print(today)

# convert today's date to string and set year, month and day as variables from this
today = str(today)
year = int(today[0:4])
month = int(today[5:7])
day = int(today[8:])

# create a list with number of days in each month (one for leap year and one for non leap year)
days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
leapyear_days = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]# if a year is divisible by 4 it is a leap year unless it is divisible by 100 and not by 400
number_of_days = 0
for years in range (0, year):
    # if the number of years is divisible by 4 and not by 100, it is a leap year so add 366 days
    if years %4 == 0 and years %100 != 0:
        number_of_days += 366
        # add the number of days in each month
        for months in range(0, month):
            number_of_days += leapyear_days[months]
    # if the number of years is divisible by 400, it is a leap year
    elif years %400 == 0:
        number_of_days += 366
        # add the number of days in each month
        for months in range(0, month):
            number_of_days += leapyear_days[months]
    # otherwise, it isn't a leap year so add 365 days
    else:
        number_of_days += 365
        # add the number of days in each month
        for months in range(0, month):
            number_of_days += days[months]

# add the number of days into this month
number_of_days += day

print(number_of_days)